#:kivy 2.1.0

<Menu>:
    canvas.before:
        Color:
            rgba: 0, 0, 0, 0
        Rectangle:
            pos: self.pos
            size: self.size
            source: "round.png"
    BoxLayout:
        orientation: "vertical"
        pos_hint: {'center_x': 0.5, 'center_y':0.5}
        size_hint: 0.25, 0.25
        Button:
            text:"Start Game"
        Button:
            text:"Exit"
        Button:
            text:"About"   